name: CI
on:
  pull_request:
    types: [opened, edited, closed, reopened]

jobs:
  ciJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # run: echo "Hello World"
