# This job only exists to trigger the octaneintegration workflow.
# This job contains no actions
name: oct-integr-dummy
on: push

jobs:
  oct_dummy:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Step
        # uses: actions/checkout@v4
        run: echo ${{github.server.url}}/${{github.repository.name}}
